Vagrant.configure("2") do |config|
	config.vm.box = "centos/7"
  config.vm.network "forwarded_port", guest: 80, host: 8888
  config.vm.network "forwarded_port", guest: 80, host: 8888, host_ip: "127.0.0.1"
  config.vm.provision "shell", inline: <<-SHELL
    sudo yum install epel-release -y

    sudo yum install nginx -y

    sudo systemctl start nginx

    systemctl start firewalld

    systemctl enable firewalld

    sudo firewall-cmd --permanent --zone=public --add-service=http 
    # sudo firewall-cmd --permanent --zone=public --add-service=https
    sudo cp -f /vagrant/www-content/* /usr/share/nginx/html
    sudo firewall-cmd --reload

    sudo systemctl enable nginx
  SHELL

end
